export interface AppDesign {
  primary: string
  primaryLight: string
  primaryDark: string
  surface: string
  bg: string
  text: string
  textMuted: string
  border: string
  fontDisplay: string
  fontBody: string
  radius: string
  buttonStyle: 'pill' | 'square'
}

/**
 * Converts HSL to Hex (simplified for UI tokens)
 */
function hslToHex(h: number, s: number, l: number): string {
  l /= 100
  const a = (s * Math.min(l, 1 - l)) / 100
  const f = (n: number) => {
    const k = (n + h / 30) % 12
    const color = l - a * Math.max(Math.min(k - 3, 9 - k, 1), -1)
    return Math.round(255 * color)
      .toString(16)
      .padStart(2, '0')
  }
  return `#${f(0)}${f(8)}${f(4)}`
}

export function deriveAppDesign(businessType: string, businessName: string, city: string = ''): AppDesign {
  // Step 1: Pick base hue from business type
  const BASE_HUES: Record<string, number> = {
    kirana: 28, // warm amber
    grocery: 28,
    dairy: 210, // clean blue
    tailor: 280, // purple
    salon: 340, // rose
    restaurant: 16, // deep orange-red
    medical: 190, // teal
    hardware: 35, // brown-orange
    transport: 220, // navy
    coaching: 260, // violet
    default: 200, // neutral blue
  }

  // Step 2: Derive saturation from city tier
  const TIER1 = ['Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Hyderabad', 'Pune', 'Kolkata']
  const saturation = TIER1.includes(city) ? 65 : 80

  // Step 3: Pick lightness variation based on business name hash
  const nameHash = businessName.split('').reduce((a, c) => a + c.charCodeAt(0), 0)
  const lightnessVariant = [45, 50, 55, 48, 52][nameHash % 5]

  const hue = BASE_HUES[businessType.toLowerCase()] ?? BASE_HUES.default

  // Typography pair
  const FONT_PAIRS: Record<string, { display: string; body: string }> = {
    kirana: { display: 'Sora', body: 'DM Sans' },
    dairy: { display: 'Plus Jakarta Sans', body: 'Inter' },
    salon: { display: 'Playfair Display', body: 'Lato' },
    restaurant: { display: 'Fraunces', body: 'Source Sans 3' },
    medical: { display: 'Plus Jakarta Sans', body: 'Inter' },
    hardware: { display: 'Barlow', body: 'DM Sans' },
    transport: { display: 'Space Grotesk', body: 'Inter' },
    coaching: { display: 'Outfit', body: 'DM Sans' },
    tailor: { display: 'Cormorant Garamond', body: 'Lato' },
    default: { display: 'Inter', body: 'DM Sans' },
  }
  const fonts = FONT_PAIRS[businessType.toLowerCase()] ?? FONT_PAIRS.default

  const RADIUS_MAP: Record<string, string> = {
    salon: '1.25rem',
    medical: '0.5rem',
    hardware: '0.375rem',
    kirana: '0.75rem',
    restaurant: '1rem',
    default: '0.75rem',
  }

  const BUTTON_STYLES: Record<string, 'pill' | 'square'> = {
    salon: 'pill',
    medical: 'square',
    hardware: 'square',
    kirana: 'pill',
    restaurant: 'pill',
    default: 'pill',
  }

  return {
    primary: hslToHex(hue, saturation, lightnessVariant),
    primaryLight: hslToHex(hue, saturation, lightnessVariant + 45),
    primaryDark: hslToHex(hue, saturation, Math.max(lightnessVariant - 15, 10)),
    surface: '#FFFFFF',
    bg: hslToHex(hue, 20, 97), // very light tint
    text: '#1A1917',
    textMuted: '#6B6560',
    border: hslToHex(hue, 30, 90),
    fontDisplay: fonts.display,
    fontBody: fonts.body,
    radius: RADIUS_MAP[businessType.toLowerCase()] ?? RADIUS_MAP.default,
    buttonStyle: BUTTON_STYLES[businessType.toLowerCase()] ?? BUTTON_STYLES.default,
  }
}

export function generateGlobalsCss(design: AppDesign): string {
  return `
@tailwind base;
@tailwind components;
@tailwind utilities;

/* AUTO-GENERATED by MAYA — DO NOT EDIT MANUALLY */
:root {
  --color-primary: ${design.primary};
  --color-primary-light: ${design.primaryLight};
  --color-primary-dark: ${design.primaryDark};
  --color-surface: ${design.surface};
  --color-bg: ${design.bg};
  --color-text: ${design.text};
  --color-text-muted: ${design.textMuted};
  --color-border: ${design.border};
  --font-display: '${design.fontDisplay}', sans-serif;
  --font-body: '${design.fontBody}', sans-serif;
  --radius: ${design.radius};
  --radius-sm: calc(${design.radius} * 0.67);
  --radius-lg: calc(${design.radius} * 1.5);
}

body {
  background-color: var(--color-bg);
  color: var(--color-text);
  font-family: var(--font-body);
}

h1, h2, h3, h4, h5, h6 {
  font-family: var(--font-display);
}

.button-radius {
  border-radius: var(--radius);
}
`
}

export const FEATURE_TIERS: Record<string, { tier0: string[]; tier1: string[]; tier2: string[] }> = {
  kirana: {
    tier0: [
      'product_listing',
      'product_detail',
      'basic_cart',
      'simple_checkout',
      'order_confirmation',
      'admin_product_crud',
      'admin_order_view',
    ],
    tier1: ['product_search', 'product_categories', 'order_tracking_status'],
    tier2: ['product_variants', 'discount_codes', 'customer_order_history'],
  },
  restaurant: {
    tier0: [
      'menu_display',
      'item_detail',
      'basic_order',
      'order_confirmation',
      'admin_menu_crud',
      'admin_order_board',
    ],
    tier1: ['menu_categories', 'item_customization', 'order_status_tracking'],
    tier2: ['special_items_banner', 'order_history', 'combo_offers'],
  },
  ecommerce: {
    tier0: [
      'product_listing',
      'product_detail',
      'basic_cart',
      'simple_checkout (COD only)',
      'order_confirmation',
      'admin_product_crud',
      'admin_order_view',
    ],
    tier1: ['product_search', 'product_categories', 'order_tracking_status', 'upi_payment'],
    tier2: ['product_variants', 'discount_codes', 'customer_order_history', 'reviews'],
  },
  default: {
    tier0: [
      'home_page',
      'contact_form',
      'services_list',
      'admin_dashboard',
    ],
    tier1: ['photo_gallery', 'testimonials'],
    tier2: ['online_booking'],
  },
}
